INSERT INTO COUNTRIES_TABLE (countryID, country_name, country_iso_2, country_iso_3) VALUES (1, 'Россия', 'RU', 'RUS');
INSERT INTO COUNTRIES_TABLE (countryID, country_name, country_iso_2, country_iso_3) VALUES (2, 'Беларусь', 'BY', 'BLR');
INSERT INTO COUNTRIES_TABLE (countryID, country_name, country_iso_2, country_iso_3) VALUES (3, 'Украина', 'UA', 'UKR');

INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (1, 1, 'Адыгея', 'Адыгея');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (2, 1, 'Башкирия', 'Башкирия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (3, 1, 'Бурятия', 'Бурятия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (4, 1, 'Горный Алтай', 'Горный Алтай');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (5, 1, 'Дагестан', 'Дагестан');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (6, 1, 'Ингушетия', 'Ингушетия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (7, 1, 'Кабардино-Балкария', 'Кабардино-Балкария');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (8, 1, 'Калмыкия', 'Калмыкия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (9, 1, 'Карачаево-Черкесия', 'Карачаево-Черкесия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (10, 1, 'Карелия', 'Карелия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (11, 1, 'Коми', 'Коми');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (12, 1, 'Марийская Республика', 'Марийская Республика');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (13, 1, 'Мордовская Республика', 'Мордовская Республика');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (14, 1, 'Якутия', 'Якутия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (15, 1, 'Северная Осетия', 'Северная Осетия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (16, 1, 'Татарстан', 'Татарстан');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (17, 1, 'Тува', 'Тува');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (18, 1, 'Удмуртия', 'Удмуртия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (19, 1, 'Хакасия', 'Хакасия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (20, 1, 'Чечня', 'Чечня');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (21, 1, 'Чувашия', 'Чувашия');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (22, 1, 'Алтайский край', 'Алтайский край');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (23, 1, 'Краснодарский край', 'Краснодарский край');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (24, 1, 'Красноярский край', 'Красноярский край');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (25, 1, 'Приморский край', 'Приморский край');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (26, 1, 'Ставропольский край', 'Ставропольский край');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (27, 1, 'Хабаровский край', 'Хабаровский край');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (28, 1, 'Амурская область', 'Амурская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (29, 1, 'Архангельская область', 'Архангельская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (30, 1, 'Астраханская область', 'Астраханская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (31, 1, 'Белгородская область', 'Белгородская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (32, 1, 'Брянская область', 'Брянская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (33, 1, 'Владимирская область', 'Владимирская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (34, 1, 'Волгоградская область', 'Волгоградская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (35, 1, 'Вологодская область', 'Вологодская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (36, 1, 'Воронежская область', 'Воронежская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (37, 1, 'Ивановская область', 'Ивановская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (38, 1, 'Иркутская область', 'Иркутская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (39, 1, 'Калининградская область', 'Калининградская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (40, 1, 'Калужская область', 'Калужская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (41, 1, 'Камчатская область', 'Камчатская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (42, 1, 'Кемеровская область', 'Кемеровская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (43, 1, 'Кировская область', 'Кировская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (44, 1, 'Костромская область', 'Костромская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (45, 1, 'Курганская область', 'Курганская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (46, 1, 'Курская область', 'Курская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (47, 1, 'Ленинградская область', 'Ленинградская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (48, 1, 'Липецкая область', 'Липецкая область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (49, 1, 'Магаданская область', 'Магаданская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (50, 1, 'Московская область', 'Московская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (51, 1, 'Мурманская область', 'Мурманская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (52, 1, 'Нижегородская область', 'Нижегородская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (53, 1, 'Новгородская область', 'Новгородская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (54, 1, 'Новосибирская область', 'Новосибирская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (55, 1, 'Омская область', 'Омская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (56, 1, 'Оренбургская область', 'Оренбургская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (57, 1, 'Орловская область', 'Орловская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (58, 1, 'Пензенская область', 'Пензенская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (59, 1, 'Пермская область', 'Пермская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (60, 1, 'Псковская область', 'Псковская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (61, 1, 'Ростовская область', 'Ростовская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (62, 1, 'Рязанская область', 'Рязанская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (63, 1, 'Самарская область', 'Самарская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (64, 1, 'Саратовская область', 'Саратовская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (65, 1, 'Сахалинская область', 'Сахалинская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (66, 1, 'Свердловская область', 'Свердловская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (67, 1, 'Смоленская область', 'Смоленская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (68, 1, 'Тамбовская область', 'Тамбовская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (69, 1, 'Тверская область', 'Тверская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (70, 1, 'Томская область', 'Томская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (71, 1, 'Тульская область', 'Тульская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (72, 1, 'Тюменская область', 'Тюменская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (73, 1, 'Ульяновская область', 'Ульяновская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (74, 1, 'Челябинская область', 'Челябинская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (75, 1, 'Читинская область', 'Читинская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (76, 1, 'Ярославская область', 'Ярославская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (77, 1, 'Москва', 'Москва');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (78, 1, 'Санкт-Петербург', 'Санкт-Петербург');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (79, 1, 'Еврейская автономная область', 'Еврейская автономная область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (80, 1, 'Агинский Бурятский АО', 'Агинский Бурятский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (81, 1, 'Коми-Пермяцкий АО', 'Коми-Пермяцкий АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (82, 1, 'Корякский АО', 'Корякский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (83, 1, 'Ненецкий АО', 'Ненецкий АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (84, 1, 'Таймырский АО', 'Таймырский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (85, 1, 'Усть-Ордынский Бурятский АО', 'Усть-Ордынский Бурятский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (86, 1, 'Ханты-Мансийский АО', 'Ханты-Мансийский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (87, 1, 'Чукотский АО', 'Чукотский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (88, 1, 'Эвенкийский АО', 'Эвенкийский АО');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (89, 1, 'Ямало-Ненецкий АО', 'Ямало-Ненецкий АО');     
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (90, 2, 'Витебская область', 'Витебская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (91, 2, 'Могилевская область', 'Могилевская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (92, 2, 'Минская область', 'Минская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (93, 2, 'Гродненская область', 'Гродненская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (94, 2, 'Гомельская область', 'Гомельская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (95, 2, 'Брестская область', 'Брестская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (96, 3, 'Республика Крым', 'Республика Крым');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (97, 3, 'Винницкая область', 'Винницкая область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (98, 3, 'Волынская область', 'Волынская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (99, 3, 'Днепропетровская область', 'Днепропетровская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (100, 3, 'Донецкая область', 'Донецкая область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (101, 3, 'Житомирская область', 'Житомирская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (102, 3, 'Закарпатская область', 'Закарпатская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (103, 3, 'Запорожская область', 'Запорожская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (104, 3, 'Ивано-Франковская область', 'Ивано-Франковская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (105, 3, 'Киевская область', 'Киевская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (106, 3, 'Кировоградская область', 'Кировоградская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (107, 3, 'Луганская область', 'Луганская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (108, 3, 'Львовская область', 'Львовская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (109, 3, 'Николаевская область', 'Николаевская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (110, 3, 'Одесская область', 'Одесская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (111, 3, 'Полтавская область', 'Полтавская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (112, 3, 'Ровенская область', 'Ровенская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (113, 3, 'Сумская область', 'Сумская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (114, 3, 'Тернопольская область', 'Тернопольская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (115, 3, 'Харьковская область', 'Харьковская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (116, 3, 'Херсонская область', 'Херсонская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (117, 3, 'Хмельницкая область', 'Хмельницкая область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (118, 3, 'Черкасская область', 'Черкасская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (119, 3, 'Черниговская область', 'Черниговская область');
INSERT INTO ZONES_TABLE (zoneID, countryID, zone_code, zone_name) VALUES (120, 3, 'Черновицкая область', 'Черновицкая область');